
title: ProofZoom
rl: "https://proofzoom.org"
baseurl: ""

markdown: kramdown
permalink: pretty

collections:
  entries:
    output: true
    permalink: /entries/:name/

exclude:
  - Gemfile
  - Gemfile.lock
  - PROOFZOOM-MANUAL-FINAL.md